import = [
    # "~/.config/alacritty/tokyonight.toml",
    "~/.config/alacritty/carbon.toml",
    "~/.config/alacritty/font.toml",
]

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[window]
padding         = { x = 11, y = 13 }
dynamic_padding = true
opacity         = 1
