[font]
size = 14
offset = { x = 0, y = 8 }
glyph_offset = { x = 0, y = 4 }

[font.bold]
family = "jetbrains mono nerd font"
style  = "bold"

[font.bold_italic]
family = "jetbrains mono nerd font"
style  = "bold italic"

[font.italic]
family = "jetbrains mono nerd font"
style  = "italic"

[font.normal]
family = "jetbrains mono nerd font"
style  = "regular"
